name: Infrastructure Pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  traffic-light-pipeline:
    uses: vpapakir/iac-pipeline-templates/.github/workflows/traffic-light-pipeline.yml@v0.0.9
    with:
      ci-tool: 'gh_actions'
      default-cloud-provider: 'aws'
    secrets:
      terraform-cloud-token: ${{ secrets.TF_CLOUD_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      civo-token: ${{ secrets.CIVO_TOKEN }}